### PR TITLE
Logout

### PR DESCRIPTION
**Pull request by atomiccupcake**
Setting this as a draft, because the API endpoint doesn't seem to actually work. I get a 500 error pq: relation "sessions" does not exist. Maybe my database is out of date or something? Feel free to take over the branch. Everything is styled. Moved latency to hovering on the logo instead.

### CODE REVIEW

**Comment by domino14** [comment]
I merged in andy's fix.  @atomiccupcake could you rebase from master and see if the logout works fine?

**Review by domino14 — APPROVED** [review]

**Comment by atomiccupcake** [comment]
> I merged in andy's fix. @atomiccupcake could you rebase from master and see if the logout works fine? Once you test it let me know so I can deploy the previous fix to the backend first.

Not really.

First, I stay logged in until I refresh the browser or get redirected to another . (I can send a chat message as myself or start a game, but I'm logged out when I get TO the game). I can force a refresh or something in the browser.

I am also still seeing those logged out users in presences, long after the refresh. That could be my local don't log people out when the socket drops override. I'll remove that and see if it fixes this part.

**Comment by domino14** [comment]
yeah Logout should definitely force a refresh. Deleting the session doesn't actually disconnect the socket connection which is why you can still chat.

**Comment by atomiccupcake** [comment]
Okay. I refresh the page and that successfully keeps the user from interacting as their self, but something is going to need to be done about presences/redis on your end. It's keeping everybody. If you want to merge this and let that bug be outstanding, it's up to you.

**Comment by domino14** [comment]
Ok great. I'll merge this by tomorrow.

**Pull request merged**
